### PR TITLE
pkg_install throws proper errors

### LINKED ISSUE #33: Better failure on solution error
Instead of this:
```
❯ pkg_install("foobar")
  Updating CRAN metadata
✔ CRAN metadata current
  Updating BioConductor metadata
✔ BioC metadata current
✔ Found 0 dependencies for 1 packages in 2.1s
✔ No downloads are needed
Error: Columns `ref`, `package`, `type`, `version`, `file` must be 1d atomic vectors or lists
In addition: Warning message:
In structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

```
❯ pkg_install(c("r-lib/usethis", "cran::usethis"))
  Updating CRAN metadata
✔ CRAN metadata current
✔ Found 64 dependencies for 2 packages in 2.1s
✔ No downloads are needed
Error: Columns `ref`, `package`, `type`, `version`, `file` must be 1d atomic vectors or lists
In addition: Warning message:
In structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #33 

When a `solve()` fails:
```
❯ pkg_install(c("r-lib/usethis", "cran::usethis"))
  Updating CRAN metadata
✔ CRAN metadata current
✔ Found 62 dependencies for 2 packages in 1.6s

Error: Cannot install packages:
  * Cannot install package `usethis`.
  - `cran::usethis`, conflicts with `r-lib/usethis`
  - `installed::/Users/gaborcsardi/r_pkgs/usethis`, conflicts with `r-lib/usethis`
  - `r-lib/usethis`, conflicts with `cran::usethis`
```

or when a download fails:
```
❯ pkg_install("r-lib/usethis", lib = "/tmp/lib")
  Updating CRAN metadata
✔ Updated CRAN metadata
✔ Found 23 dependencies for 1 packages in 2.9s
✔ 38 packages, in 6.5s

Error: Cannot download some packages:
Failed to download Rcpp from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/Rcpp_0.12.14.tgz`.
Failed to download rstudioapi from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rstudioapi_0.7.tgz`.
Failed to download knitr from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/knitr_1.18.tgz`.
Failed to download rematch2 from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rematch2_2.0.1.tgz`.
Failed to download whisker from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/whisker_0.3-2.tgz`.
Failed to download magrittr from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/magrittr_1.5.tgz`.
```

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Updated to sit on top of #32. FYI.

File: R/package.R [hunk 1]
```diff
@@ -6,40 +6,75 @@
...
   # Actually download packages as needed
   r$download_solution()
 
+  # Download errors?
+  dl <- r$get_solution_download()
+  if (any(bad <- tolower(dl$data$download_status) == "failed")) {
+    msgs <- vcapply(
+      which(bad),
+      function(i) {
+        urls <- paste(backtick(dl$data$sources[[i]]), collapse = ", ")
```
Comment (jimhester) [inline R/package.R]: You can use `glue::collapse(backtick(dl$data$sources[[i]]), ",")` for this if you want...

File: R/package.R [hunk 2]
```diff
@@ -6,40 +6,75 @@
...
   r <- remotes$new(pkg, library = lib)
 
   # Solve the dependency graph
   r$solve()
+  sol <- r$get_solution()
+
+  # Solution error?
+  if (sol$status != "OK") {
+    msg <- paste(format(sol$failures), collapse = "\n")
+    cat("\n")
```
Comment (jimhester) [inline R/package.R]: Why do we need an extra newline here? Because the pkgdepends progress bar does not add one when resolution completes?

Comment (gaborcsardi) [reply R/package.R]: Because the error block might be several lines, and it is good to separate it from the rest of the output.

File: R/package.R (hunk 1 above)
Comment (gaborcsardi) [reply R/package.R]: Yeah, I think I'll just write a helper function, `fmt_items()` or sg like that. Both the `paste` and the `glue` one are sub-optimal.

**Comment by gaborcsardi** [comment]
> I think putting the two error checking blocks in helper functions would be cleaner. Maybe
> stop_for_solution_error() and stop_for_download_error()?

Yes.

> Why does pkgdepends not signal an error directly if the solution or download fails?

Because often you can still continue, e.g. in the `repoman` use case. But even for `pkgman`, if you fail to download a suggested package for a large installation, you often want to just continue. (The API for overriding failures is yet to come.)

**Comment by jimhester** [comment]
Ok that makes sense.

**Comment by gaborcsardi** [comment]
OK, I put the `stop_for_*` functions in `pkgdepends`, it feels like they belong there. This makes this PR rather trivial.

**Comment by gaborcsardi** [comment]
Thanks!
